builds:
  - binary: polyrule
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  prerelease: autorelease

universal_binaries:
  - replace: true

checksum:
  name_template: 'checksums.txt'

dockers:
  - dockerfile: '{{ .Env.DOCKERFILE }}'
  - image_templates:
    - "ermos/polyrule:latest"
    - "ermos/polyrule:{{ .Tag }}"

snapcrafts:
  -
    name: polyrule
    summary: Software to compile validator rules into multiple languages.
    description: Software to compile validator rules into multiple languages.
    publish: true
    grade: stable
    # https://snapcraft.io/docs/reference/confinement
    confinement: strict
    license: MIT
    base: bare
    apps:
      polyrule:
        plugs: ["system-files"]