builds:
  - binary: polyrule
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  prerelease: autorelease

universal_binaries:
  - replace: true

checksum:
  name_template: 'checksums.txt'

snapcrafts:
  -
    name: polyrule
    summary: Software to compile validator rules into multiple languages.
    description: Software to compile validator rules into multiple languages.
    publish: false
    grade: stable
    # https://snapcraft.io/docs/reference/confinement
    confinement: strict
    license: MIT
    base: core22
    apps:
      polyrule:
        command: bin/polyrule
        plugs: [ "system-files"]