builds:
  - binary: polyrule
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - # Replacements for GOOS and GOARCH in the archive name.
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      amd64: x86_64

    # Can be used to change the archive formats for specific GOOS.
    format_overrides:
      - goos: windows
        format: zip

    # Additional files/template/globs you want to add to the archive.
    files:
      - LICENSE
      - README.md

release:
  prerelease: autorelease

universal_binaries:
  - replace: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}"

snapcrafts:
  -
    name: polyrule
    publish: true
    summary: Software to compile validator rules into multiple languages.
    description: Software to compile validator rules into multiple languages.
    channel_templates:
      - edge
      - beta
      - candidate
      - stable
      - '{{ .Major }}.{{ .Minor }}/edge'
      - '{{ .Major }}.{{ .Minor }}/beta'
      - '{{ .Major }}.{{ .Minor }}/candidate'
      - '{{ .Major }}.{{ .Minor }}/stable'

    grade: stable
    # https://snapcraft.io/docs/reference/confinement
    confinement: strict
    license: MIT
    base: core18
    apps:
      polyrule:
        command: polyrule
        plugs: ["system-files"]