name: goreleaser

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"

permissions:
  contents: write
  # packages: write
  # issues: write

env:
  SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.snapcraft_token }}

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.1'
          cache: true
      - name: Install Snapcraft
        run: |
          # Required to avoid snapcraft install failure
          sudo chown root:root /
          # "--classic" is needed for the GitHub action runner
          # environment.
          sudo snap install snapcraft --classic
          # Allow other parts to access snap binaries
          echo /snap/bin >> "$GITHUB_PATH"
      # More assembly might be required: Docker logins, GPG, etc. It all depends
      # on your needs.
      - uses: goreleaser/goreleaser-action@v4
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro':
          distribution: goreleaser
          version: ${{ env.GITHUB_REF_NAME }}
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro'
          # distribution:
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}