name: goreleaser

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"

permissions:
  contents: write
  # packages: write
  # issues: write

env:
  # snapcraft export-login --snaps {packageName} --channels edge,edge/* --acls package_access,package_push,package_update,package_release -
  SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.snapcraft_token }}

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.1'
          cache: true
      - name: Install Snapcraft
        run: |
          # Required to avoid snapcraft install failure
          sudo chown root:root /
          # "--classic" is needed for the GitHub action runner
          # environment.
          sudo snap install snapcraft --classic
          # Allow other parts to access snap binaries
          echo /snap/bin >> "$GITHUB_PATH"
      - name: Create default snapcraft folder (prevent concurrency error)
        run: |
          mkdir -p $HOME/.cache/snapcraft/download
          mkdir -p $HOME/.cache/snapcraft/stage-packages
      # More assembly might be required: Docker logins, GPG, etc. It all depends
      # on your needs.
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: ${{ env.GITHUB_REF_NAME }}
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}