name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - '*'

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.1'
          cache: true
      # More assembly might be required: Docker logins, GPG, etc. It all depends
      # on your needs.
      - uses: goreleaser/goreleaser-action@v4
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro':
          distribution: goreleaser
          version: ${{ env.GITHUB_REF_NAME }}
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro'
          # distribution:
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}

      - name: List snapshot images
        run: |
          docker image ls --format "{{.Repository}}:{{.Tag}}" | \
            grep -e "$GITHUB_REPOSITORY:.*$(git rev-parse --short HEAD).*" | \
            paste -sd ' ' /dev/stdin > images
      - name: Push snapshot images
        run: |
          cat images | xargs -d ' ' -I{} -n1 sh -c "docker push {}"
      - name: Create and push manifest for :snapshot tag
        run: |
          docker manifest create $GITHUB_REPOSITORY:snapshot $(cat images)
          docker manifest push $GITHUB_REPOSITORY:snapshot